package com.javier.inmuebles.modelos;
// Generated 23-jul-2014 17:20:13 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Propietario generated by hbm2java
 */
@Entity
@Table(name="Propietario"
    ,catalog="teide2014"
)
public class Propietario  implements java.io.Serializable {


     private Integer idPropietario;
     private String nombre;
     private String dni;
     private Set<Inmueble> inmuebles = new HashSet<Inmueble>(0);

    public Propietario() {
    }

	
    public Propietario(String nombre, String dni) {
        this.nombre = nombre;
        this.dni = dni;
    }
    public Propietario(String nombre, String dni, Set<Inmueble> inmuebles) {
       this.nombre = nombre;
       this.dni = dni;
       this.inmuebles = inmuebles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPropietario", unique=true, nullable=false)
    public Integer getIdPropietario() {
        return this.idPropietario;
    }
    
    public void setIdPropietario(Integer idPropietario) {
        this.idPropietario = idPropietario;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="dni", nullable=false, length=45)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="propietario")
    public Set<Inmueble> getInmuebles() {
        return this.inmuebles;
    }
    
    public void setInmuebles(Set<Inmueble> inmuebles) {
        this.inmuebles = inmuebles;
    }




}


